### ISSUE TITLE
Allow user to save other settings, but NOT username/password

### ISSUE THREAD

**Issue by MailYouLater** [jsastriawan/mc2router#2]
As soon as you save any other settings (e.g. setting up a custom tool, or setting the path to one of the predefined tools) the server address, username, and password used to connect all get saved too.

As a work around, if you don't want to save the username and password, you can make a point to configure the tool paths, and/or custom tool _before_ you enter your user details, or you can open the `config.json` file afterward and remove them.

It would be nice however, if there was an option to not save the user details, so that they don't get automatically saved when you decide to configure a new custom tool.

**Comment by jsastriawan** [comment]
Good idea, I will add check box to enable/disable autosave username and password. This is a good safety measure.

**Comment by jsastriawan** [comment]
This has been addressed by password obfuscation and checkbox to save password.
